### ISSUE TITLE
Awesome template does not generate a .tex file

### ISSUE THREAD

**Issue by ladywithhat** [hacksalot/HackMyResume#98] opened 2016-01-08 15:56 UTC
Hello,

making a CV with the awesome template: `hackmyresume BUILD test.json to test.all -t awesome` does not generate a .tex file for further processing.

Please see below:
```
Resume_generator $ hackmyresume BUILD test.json to test.tex -t awesome
*** HackMyResume v1.4.2 ***
The awesome theme doesn't support the tex format.

Resume_generator $ hackmyresume BUILD test.json to test.latex -t awesome
*** HackMyResume v1.4.2 ***
The awesome theme doesn't support the latex format.

Resume_generator $ hackmyresume BUILD test.json to test.all -t awesome
*** HackMyResume v1.4.2 ***
Reading resume: test.json
Applying AWESOME theme (1 format)
Generating LATEX resume: test.latex
Generating JSON resume: test.json
Generating YML  resume: test.yml
The AWESOME theme says: "Don't forget to run 
'xelatex <myresume.tex>' in the generated latex/examples 
folder to complete your resume build! For more info, see the 
theme README at 
https://github.com/fluentdesk/fresh-themes/blob/master/themes/awesome/README.md."
Resume_generator $ find . -name test.tex
Resume_generator $ find . -name test.latex
Resume_generator $
```

**Comment by hacksalot** [comment] 2016-01-08 16:20
Thanks for the heads up, investigating.

**Comment by ladywithhat** [comment] 2016-01-12 13:12
.latex file is not generated with 1.6.0 (please see below)
```
hackmyresume BUILD test.json to test.latex -t awesome

*** HackMyResume v1.6.0 ***
Applying AWESOME theme (1 formats)
Generating LATEX resume: test.latex
The AWESOME theme says: "Don't 
forget to run 'xelatex <myresume.tex>' in the 
generated latex/examples folder to complete your 
resume build! For more info, see the theme README 
at 
https://github.com/fluentdesk/fresh-themes/blob/master/themes/awesome/README.md."

$ find . -name test.latex
```

**Comment by hacksalot** [comment] 2016-01-12 13:15
Hi, 1.6.0 is still in progress but we'll double-check the AWESOME generation and hopefully get this closed out today.

**Comment by hacksalot** [comment] 2016-02-01 01:23
Unable to reproduce this issue in 1.7.x. Closing, but feel free to comment or open another issue if you're still experiencing this. Thanks~

**Closed by hacksalot** 2016-02-01 01:23 UTC
Labels: bug, LaTeX

**Comment by mtantawy** [comment] 2016-02-08 21:14
1.7.4
```
$ hackmyresume build resume.json to out/resume.all -t awesome

*** HackMyResume v1.7.4 ***
Reading FRESH resume: resume.json
Applying AWESOME theme (3 formats)
Generating LATEX resume: out/resume.latex
Error: 
Generating JSON resume: out/resume.json
Generating YML  resume: out/resume.yml
```
