### ISSUE TITLE
*.json to file.(specific format) and template option does not work

### ISSUE THREAD

**Issue by ladywithhat** [hacksalot/HackMyResume#97] opened 2016-01-08 15:54 UTC
Hello,

Only the .all option does work if a specific template via -t command is selected and build.
If a specific filetype is selected generation of a cv prompts: 
```
Resume_generator $ hackmyresume BUILD test.json to test.html -t modern

*** HackMyResume v1.4.2 ***
The modern theme doesn't support the html format.
```
However, the .all option prompts:
```
Resume_generator $ hackmyresume BUILD test.json to test.all -t modern

*** HackMyResume v1.4.2 ***
Reading resume: test.json
Applying MODERN theme (5 formats)
Generating TXT  resume: test.txt
Generating MD   resume: test.md
Generating DOC  resume: test.doc
Generating HTML resume: test.html
Generating PDF  resume: test.pdf
Generating JSON resume: test.json
Generating YML  resume: test.yml
Generating PNG  resume: test.png
The MODERN theme says: "To get colored skill 
progress bars, make sure your resume includes a `level` 
element for each skill!"
```

Shouldn't also the first parameter of test.html generate a .html file instead of prompting this error?

**Comment by hacksalot** [comment] 2016-01-08 16:19
Thanks for the report @ladywithhat -- this will be fixed in today's 1.5.0 release. Will update here.

**Comment by ladywithhat** [comment] 2016-01-09 01:48
thank you for responding so fast.
A other problem occurs:
```hackmyresume BUILD test.json to test.pdf -t modern```
prompts a file called ```test.pdf.html``` instead of ```test.pdf```
I believe it is a bug as well.

**Comment by hacksalot** [comment] 2016-01-09 02:30
Thanks for the update. Are you able to successfully run, and generate a PDF, using wkhtmltopdf directly?

    wkhtmltopdf <source>.html <target>.pdf

You can also try with Phantom (assuming you have Phantom.js installed and path-accessible):

    hackmyresume test.json to test.pdf -t modern --pdf phantom

One reason for there to be a `.pdf.html` but no `.pdf` is when PDF generation fails. (The `.pdf.html` is an intermediate format. It's what HMR passes to wkhtmltopdf and/or Phantom to generate the PDF. After a successful run, you should end up with both a `.pdf.html` and a `.pdf`).

Based on your answer to that, we should be able to resolve this one way or the other.

**Comment by ladywithhat** [comment] 2016-01-09 11:52
` wkhtmltopdf <source>.html <target>.pdf`: works and generates a pdf

Phantom does not work either
```$ hackmyresume BUILD test.json to test.pdf -t modern --pdf phantom
*** HackMyResume v1.5.2 ***
Reading resume: test.json
Applying MODERN theme (5 formats)
Generating PDF  resume (with phantom): test.pdf
ERROR: [object Object]```

**Comment by hacksalot** [comment] 2016-01-09 12:58
Thanks for testing this. The Phantom.js error looks to be a duplicate of #99 and a fix is in progress. As to the original error you were experiencing, two options:

1. You can send me or paste here your resume `.json` (replace private fields as necessary) and I'll test against it directly and hopefully roll a fix into today's release.

2. Or, wait for v1.6.0 (tomorrow) which has detailed debug info through the `--debug` flag.

We've had a few of these errors and they're usually quick fixes, once identified. Thanks!

**Comment by ladywithhat** [comment] 2016-01-10 00:29
Thx for checking!

The testfile is just an example file:
please change to resume.json
[resume.json.txt](https://github.com/hacksalot/HackMyResume/files/83893/resume.json.txt)

**Comment by ladywithhat** [comment] 2016-01-12 13:09
with 1.6.0 and same file:
```
hackmyresume BUILD test.json to test5.pdf -t modern
*** HackMyResume v1.6.0 ***
Applying MODERN theme (5 formats)
Generating PDF  resume: test5.pdf
{ fluenterror: undefined,
  inner: [TypeError: undefined is not a function],
  stack: 'TypeError: undefined is not a function\n    at Class.engines.wkhtmltopdf (/usr/local/lib/node_modules/hackmyresume/src/generators/html-pdf-cli-generator.js:82:18)\n    at Class.module.exports.TemplateGenerator.extend.onBeforeSave (/usr/local/lib/node_modules/hackmyresume/src/generators/html-pdf-cli-generator.js:44:31)\n    at /usr/local/lib/node_modules/hackmyresume/src/generators/template-generator.js:156:32\n    at Array.forEach (native)\n    at Class.module.exports.BaseGenerator.extend.generate (/usr/local/lib/node_modules/hackmyresume/src/generators/template-generator.js:144:21)\n    at Class.single (/usr/local/lib/node_modules/hackmyresume/src/verbs/build.js:163:30)\n    at Class.<anonymous> (/usr/local/lib/node_modules/hackmyresume/src/verbs/build.js:99:24)\n    at /usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:73:21\n    at Function._.each._.forEach (/usr/local/lib/node_modules/hackmyresume/node_modules/underscore/underscore.js:153:9)\n    at Class.build (/usr/local/lib/node_modules/hackmyresume/src/verbs/build.js:98:7)' }
ERROR: [object Object]
The MODERN theme says: "To get 
colored skill progress bars, make sure your resume 
includes a `level` element for each 
skill!"
```

**Comment by hacksalot** [comment] 2016-01-12 13:22
@ladywithhat can you verify your Node.js version and OS version for me? This look to be related to our use of `spawn` to launch wkhtmltopdf and/or Phantom. Thanks for the report -- helpful.

**Closed** 2016-01-31 17:11 UTC
Labels: bug, in progress, willfix
