### ISSUE TITLE
Error: Numerous wkhtmltopdf-related errors

### ISSUE THREAD

**Issue by Wenzel** [hacksalot/HackMyResume#58] opened 2015-12-27 20:41 UTC
I tried to use `hackmyresume` to generate a `PDF` resume.
So I installed `wkhtmltopdf` and created a new empty resume with 
~~~
hackmyresume NEW resume.json
~~~
The I tried to build this resume with
~~~
hackmyresume BUILD resume.json TO out/resume.pdf
~~~
And I got the following error
~~~
*** HackMyResume v1.2.2 ***
Reading SOURCE resume: resume.json
Applying MODERN theme (7 formats)
Generating PDF resume: out/resume.pdf

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: loaded the Generic plugin
    at Socket.<anonymous> (/usr/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
~~~

Is it an error from `hackmyresume` ? Or is it only related to the `wkhtmltopdf` node module ?

Thanks !

**Comment by robertmain** [comment] 2015-12-27 22:39
It's probably due to wkhtmltopdf not being in your path - also, possible duplicate of #51 ?

**Comment by pmbenjamin** [comment] 2015-12-29 18:21
@Wenzel , @robertmain is correct. I got the same error on Windows 10. My steps that fixed it:
1. Added the installed path (C:\Program Files\wkhtmltopdf\bin - your path may be different) to the PATH system environment variable
2. closed current bash prompt, opened new bash prompt
3. hackmyresume BUILD resume.json TO out/resume.all (or just out/resume.pdf) 

It worked.

**Comment by hacksalot** [comment] 2015-12-29 18:43
Thanks @robertmain @pmbenjamin @Wenzel. These errors are handled more gracefully in the upcoming v1.3.0 per #51, and if you don't actually have wkhtmltopdf installed and path-accessible, it will notify you (but not error out or halt processing).

**Comment by Wenzel** [comment] 2015-12-29 19:10
@pmbenjamin that's weird because I'm sure that `wkhtmltopdf` is accessible in my `PATH`, in a standard location (`/usr/bin/wkhtmltopdf`).
I will wait for your `v1.3.0` release to see if it gives more information.

**Comment by hacksalot** [comment] 2015-12-29 19:27
@Wenzel do you get the same error when running a [sample resume](https://raw.githubusercontent.com/fluentdesk/jane-q-fullstacker/master/resume/jane-resume.json)?

**Comment by Wenzel** [comment] 2015-12-29 19:29
@hacksalot => Yes
~~~
╭─wenzel@localhost  ~/ownCloud/Documents/job ‹ruby-2.2.1› 
╰─$ hackmyresume BUILD jane-resume.json TO out/resume.all

*** HackMyResume v1.2.2 ***
Reading SOURCE resume: jane-resume.json
Applying MODERN theme (7 formats)
Generating DOC resume: out/resume.doc
Generating HTML resume: out/resume.html
Generating MD resume: out/resume.md
Generating PDF resume: out/resume.pdf
Generating TXT resume: out/resume.txt
Generating JSON resume: out/resume.json
Generating YML resume: out/resume.yml

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: loaded the Generic plugin
    at Socket.<anonymous> (/usr/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
╭─wenzel@localhost  ~/ownCloud/Documents/job ‹ruby-2.2.1› 
╰─$ which wkhtmltopdf                                                                                                                                                 8 ↵
/usr/bin/wkhtmltopdf
~~~

**Comment by pmbenjamin** [comment] 2015-12-30 00:43
@Wenzel now that we know where `wkhtmltopdf` is installed, can you also provide us your $PATH variable (e.g. `echo $PATH`)?

**Comment by Wenzel** [comment] 2015-12-30 00:46
@pmbenjamin sure !
here is my `$PATH` (don't pay attention to `rvm`)
~~~
╰─$ echo $PATH
/home/wenzel/.rvm/gems/ruby-2.2.1/bin:/home/wenzel/.rvm/gems/ruby-2.2.1@global/bin:/home/wenzel/.rvm/rubies/ruby-2.2.1/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/home/wenzel/bin:/usr/local/sbin:/usr/sbin:/home/wenzel/.rvm/bin:/home/wenzel/bin
~~~

**Comment by pmbenjamin** [comment] 2015-12-30 01:08
@Wenzel what OS are you on? which flavor did you install and which architecture (32-bit vs 64-bit)?

**Comment by Wenzel** [comment] 2015-12-30 01:10
@pmbenjamin I'm running `Fedora 23 - 64-bit`.

**Comment by pmbenjamin** [comment] 2015-12-30 01:12
@Wenzel interesting. Which flavor of wkhtmltopdf for CentOS did you install? CentOS 5, 6, or 7?

**Comment by Wenzel** [comment] 2015-12-30 01:14
@pmbenjamin 
~~~
╰─$ dnf info wkhtmltopdf.x86_64
Vérification de l'expiration des métadonnées effectuée il y a 9 days, 22:02:24 sur Sun Dec 20 04:11:35 2015.
Paquets installés
Nom         : wkhtmltopdf
Architectur : x86_64
Époque      : 0
Version     : 0.12.3
Révision    : 0.1.D20150713git79ff51e.fc23
Taille      : 800 k
Dépôt       : @System
Depuis le d : fedora
Résumé      : Simple shell utility to convert html to pdf
URL         : http://wkhtmltopdf.org/
Licence     : GPLv3+
Description : Simple shell utility to convert html to pdf using the webkit
            : rendering engine, and qt.
~~~

**Comment by pmbenjamin** [comment] 2015-12-30 01:17
did you install the Centos 7?

**Comment by Wenzel** [comment] 2015-12-30 02:15
@pmbenjamin nope, I installed the package provided by `Fedora 23` repositories.

**Comment by pmbenjamin** [comment] 2015-12-30 02:20
@Wenzel according to wkhtmltopdf, the current stable version is 0.12.2.1. Your installed version is 0.12.3. I suspect that might be the problem.

**Comment by shun-liang** [comment] 2016-01-01 21:28
@pmbenjamin I have installed wkhtmltopdf 0.12.2.1 but still have a problem similar to OP's:
```
*** HackMyResume v1.3.1 ***
Applying MODERN theme (5 formats)
Reading resume: shun_liang.json
Generating PDF resume: shun_liang.pdf
Generating PDF resume: shun_liang.pdf
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 2016-01-01 21:25:39.595 wkhtmltopdf[15559:5761185] __agent_connection_block_invoke_2: Connection error - Connection invalid
    at Socket.<anonymous> (/opt/local/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by dsdeiz** [comment] 2016-01-01 22:50
Getting the same error here as well in OSX. I think it has something to do with `wkhtmltopdf` not ignoring warnings. Tried it like so:

```
$ wkhtmltopdf jane-resume.html jane-resume.pdf
Loading pages (1/6)
Warning: SSL error ignored
2016-01-02 06:47:03.864 wkhtmltopdf[73283:1103139] __agent_connection_block_invoke_2: Connection error - Connection invalid
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
```

I get the errors but the PDF is generated. With `hackmyresume`:

```
$ hackmyresume build jane-resume.json to jane-resume.pdf

*** HackMyResume v1.3.1 ***
Applying MODERN theme (5 formats)
Reading resume: jane-resume.json
Generating PDF resume: jane-resume.pdf
Generating PDF resume: jane-resume.pdf
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: 2016-01-02 06:47:57.698 wkhtmltopdf[74295:1104863] __agent_connection_block_invoke_2: Connection error - Connection invalid
    at Socket.<anonymous> (/Users/arnoldfrench/.nvm/versions/node/v5.3.0/lib/node_modules/hackmyresume/node_modules/wkhtmltopdf/index.js:79:17)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

PDF file is empty. Common error message here is "__agent_connection_block_invoke_2: Connection error - Connection invalid".

Version of `wkhtmltopdf` is `wkhtmltopdf 0.12.2.1 (with patched qt)`.

**Comment by hacksalot** [comment] 2016-01-01 22:58
Thanks for the info, looking into this. Shortly we'll add back Phantom PDF support and make both Phantom and wkhtmltopdf optional (and do a better of catching these errors when present) but I'd like to get this issue resolved first.

**Comment by robertmain** [comment] 2016-01-03 05:23
Not sure if this belongs under this issue, but I'm getting the error described by @dsdeiz. `echo $PATH` shows: `/home/robert/.nvm/versions/node/v5.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
` and `which wkhtmltopdf` shows `/usr/bin/wkhtmltopdf` a.k.a it is in my path, but still seems not to be working correctly..

**Comment by dsdeiz** [comment] 2016-01-03 16:54
Okay, this is weird but for some reason it's working on my end now. I'm not sure if this is the solution but this is the only thing I can remember doing &mdash; I just restarted and now it's working. :smiley:

**Comment by lewiseason** [comment] 2016-01-03 18:05
I'm seeing the same issue, but unlike @dsdeiz when I run the conversion manually with `wkhtmltopdf` I don't have any errors that might be catching hackmyresume out:

```shell
➜  test git:(master) ✗ wkhtmltopdf resume.html resume.pdf
loaded the Generic plugin 
Loading page (1/2)
Printing pages (2/2)                                               
Done                                                           
➜  test git:(master) ✗ echo $?
0
```

Looks like HackMyResume isn't expecting anything on stderr?

**Comment by lewiseason** [comment] 2016-01-03 18:12
That is exactly the problem. HackMyResume bombs if `wkhtmltopdf` writes anything to stderr (it writes progress here by default).

```shell
➜  test git:(master) ✗ echo $PATH
/home/leason/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/leason/.local/bin

➜  test git:(master) ✗ cat ~/bin/wkhtmltopdf 
#!/bin/sh
/usr/bin/wkhtmltopdf $@ 2>/dev/null
```

If I do this, it works fine

**Comment by hacksalot** [comment] 2016-01-04 00:28
Possibly related : https://www.drupal.org/node/2194825.

**Comment by hacksalot** [comment] 2016-01-04 13:10
If you grab the latest off of `master` with:

`npm install hacksalot/hackmyresume`

And run:

`hackmyresume resume.json --pdf phantom`

Or:

`hackmyresume resume.json --pdf wkhtmltopdf`

You may see different behavior. This hasn't been released to NPM yet.

**Comment by hacksalot** [comment] 2016-01-07 06:05
If you're having a wkhtmltopdf-related error, please report it here. If possible, include OS, Node.js version, wkhtmltopdf version, and sanity check by running wkhtmltopdf directly on the command line first. Thanks!

**Comment by robertmain** [comment] 2016-01-07 14:20
**OS:** Windows 7
**HackMyResume Version:** 1.4.2
**NPM Version:** 3.3.6
**Node Version:** 5.0.0

--

    $ hackmyresume BUILD resume.json TO out/resume.all

    *** HackMyResume v1.4.2 ***
    Reading resume: resume.json
    Applying MODERN theme (5 formats)
    Generating TXT  resume: out\resume.txt
    Generating MD   resume: out\resume.md
    Generating DOC  resume: out\resume.doc
    Generating HTML resume: out\resume.html
    Generating PDF  resume: out\resume.pdf
    ERROR: PDF generation failed. Make sure wkhtmltopdf is installed and accessible
    from your path.
    Generating JSON resume: out\resume.json
    Generating YML  resume: out\resume.yml
    Generating PNG  resume: out\resume.png
    The MODERN theme says: "To get colored skill
    progress bars, make sure your resume includes a `level`
    element for each skill!"
    ERROR: spawn wkhtmltopdf ENOENT
    events.js:141
          throw er; // Unhandled 'error' event
          ^

    Error: spawn wkhtmltopdf ENOENT
        at exports._errnoException (util.js:860:11)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
        at onErrorNT (internal/child_process.js:344:16)
        at doNTCallback2 (node.js:450:9)
        at process._tickCallback (node.js:364:17)
        at Function.Module.runMain (module.js:459:11)
        at startup (node.js:136:18)
        at node.js:972:3


Aside from anything else, it's worth noting that I do have a skill level filled in for each skill.

**Closed** 2016-01-27 08:05 UTC
Labels: bug, PDF, willfix, wkhtmltopdf
