### ISSUE TITLE
'convert' command doesn't correctly detect input format

### ISSUE THREAD

**Issue by therealpxc** [hacksalot/HackMyResume#162] opened 2016-06-12 22:43 UTC
It always assumes 'FRESH' is the input format, so it only converts to JRS.

**Comment by et** [comment] 2016-07-25 03:02
I'm getting the same issue. I believe the cause is the following: https://github.com/hacksalot/HackMyResume/blob/master/src/verbs/convert.coffee#L72-L74
I think this should just be detecting the presence of a `basics` property. I'm not sure what the extra stuff is.

**Comment by hacksalot** [comment] 2018-01-29 14:38
Thanks guys. Fixed in the next release (1.9.0).

**Closed** 2018-02-12 12:46 UTC
Labels: bug, fixed-in-1.9.0
